name: CI Build for Docker Action
on:
  push:
    branches: [ main ]
    paths: [ hello-world-docker-action/** ]
  workflow_dispatch:
env:
  RESOURCE_GROUP_NAME: 'myResourceGroup'
  TEST_NAME: 'myTestName'

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'Lyle'
          RESOURCE_GROUP_NAME: ${{ env.RESOURCE_GROUP_NAME }}

      - name: Output time set in the container
        run: echo "TEST_NAME = ${{ steps.hello-action.outputs.TEST_NAME }} RG = ${{ steps.hello-action.outputs.RESOURCE_GROUP_NAME }} Time ${{ steps.hello-action.outputs.time }} when the action said hello"
